const TAG_COLOR = {
  TOMATO: {
    color: '#FFAB91',
    accent: '#E64A19',
  },
  TEAL: {
    color: '#80CBC4',
    accent: '#00796B',
  },
  ORANGE: {
    color: '#FFCC80',
    accent: '#F57C00',
  },
  RED: {
    color: '#EF9A9A',
    accent: '#D32F2F',
  },
  PINK: {
    color: '#F48FB1',
    accent: '#C2185B',
  },
  MAGENTA: {
    color: '#CE93D8',
    accent: '#7B1FA2',
  },
  PURPLE: {
    color: '#B39DDB',
    accent: '#512DA8',
  },
  BLUE: {
    color: '#90CAF9',
    accent: '#1976D2',
  },
  BLUE_LIGHT: {
    color: '#81D4FA',
    accent: '#0288D1',
  },
  CYAN: {
    color: '#80DEEA',
    accent: '#0097A7',
  },
  EMERALD: {
    color: '#A5D6A7',
    accent: '#388E3C',
  },
  GREEN: {
    color: '#C5E1A5',
    accent: '#388E3C',
  },
  LIME: {
    color: '#E6EE9C',
    accent: '#AFB42B',
  },
  LEMON: {
    color: '#FFF59D',
    accent: '#FBC02D',
  },
  YELLOW: {
    color: '#FFE082',
    accent: '#FFA000',
  },
  BROWN: {
    color: '#BCAAA4',
    accent: '#5D4037',
  },
  GREY: {
    color: '#757575',
    accent: '#E0E0E0',
  },
  DIM: {
    color: '#B0BEC5',
    accent: '#455A64',
  },
};

const tags = [
  {
    mal_id: 1,
    name: 'Action',
    url: 'https://myanimelist.net/anime/genre/1/Action',
    count: 5570,
    ...TAG_COLOR.ACTION,
  },
  {
    mal_id: 2,
    name: 'Adventure',
    url: 'https://myanimelist.net/anime/genre/2/Adventure',
    count: 4384,
    ...TAG_COLOR.GREEN,
  },
  {
    mal_id: 5,
    name: 'Avant Garde',
    url: 'https://myanimelist.net/anime/genre/5/Avant_Garde',
    count: 1046,
    ...TAG_COLOR.MAGENTA,
  },
  {
    mal_id: 46,
    name: 'Award Winning',
    url: 'https://myanimelist.net/anime/genre/46/Award_Winning',
    count: 258,
    ...TAG_COLOR.LEMON,
  },
  {
    mal_id: 28,
    name: 'Boys Love',
    url: 'https://myanimelist.net/anime/genre/28/Boys_Love',
    count: 192,
    ...TAG_COLOR.BLUE_LIGHT,
  },
  {
    mal_id: 4,
    name: 'Comedy',
    url: 'https://myanimelist.net/anime/genre/4/Comedy',
    count: 7715,
    ...TAG_COLOR.MAGENTA,
  },
  {
    mal_id: 8,
    name: 'Drama',
    url: 'https://myanimelist.net/anime/genre/8/Drama',
    count: 3067,
    ...TAG_COLOR.PINK,
  },
  {
    mal_id: 10,
    name: 'Fantasy',
    url: 'https://myanimelist.net/anime/genre/10/Fantasy',
    count: 5957,
    ...TAG_COLOR.PURPLE,
  },
  {
    mal_id: 26,
    name: 'Girls Love',
    url: 'https://myanimelist.net/anime/genre/26/Girls_Love',
    count: 121,
    ...TAG_COLOR.PINK,
  },
  {
    mal_id: 47,
    name: 'Gourmet',
    url: 'https://myanimelist.net/anime/genre/47/Gourmet',
    count: 220,
    ...TAG_COLOR.BROWN,
  },
  {
    mal_id: 14,
    name: 'Horror',
    url: 'https://myanimelist.net/anime/genre/14/Horror',
    count: 578,
    ...TAG_COLOR.DIM,
  },
  {
    mal_id: 7,
    name: 'Mystery',
    url: 'https://myanimelist.net/anime/genre/7/Mystery',
    count: 989,
    ...TAG_COLOR.DIM,
  },
  {
    mal_id: 22,
    name: 'Romance',
    url: 'https://myanimelist.net/anime/genre/22/Romance',
    count: 2175,
    ...TAG_COLOR.PINK,
  },
  {
    mal_id: 24,
    name: 'Sci-Fi',
    url: 'https://myanimelist.net/anime/genre/24/Sci-Fi',
    count: 3435,
    ...TAG_COLOR.TEAL,
  },
  {
    mal_id: 36,
    name: 'Slice of Life',
    url: 'https://myanimelist.net/anime/genre/36/Slice_of_Life',
    count: 1557,
    ...TAG_COLOR.GREEN,
  },
  {
    mal_id: 30,
    name: 'Sports',
    url: 'https://myanimelist.net/anime/genre/30/Sports',
    count: 809,
    ...TAG_COLOR.TEAL,
  },
  {
    mal_id: 37,
    name: 'Supernatural',
    url: 'https://myanimelist.net/anime/genre/37/Supernatural',
    count: 1540,
    ...TAG_COLOR.GREY,
  },
  {
    mal_id: 41,
    name: 'Suspense',
    url: 'https://myanimelist.net/anime/genre/41/Suspense',
    count: 452,
    ...TAG_COLOR.GREY,
  },
  {
    mal_id: 9,
    name: 'Ecchi',
    url: 'https://myanimelist.net/anime/genre/9/Ecchi',
    count: 819,
    ...TAG_COLOR.RED,
  },
  {
    mal_id: 49,
    name: 'Erotica',
    url: 'https://myanimelist.net/anime/genre/49/Erotica',
    count: 79,
    ...TAG_COLOR.RED,
  },
  {
    mal_id: 12,
    name: 'Hentai',
    url: 'https://myanimelist.net/anime/genre/12/Hentai',
    count: 1583,
    ...TAG_COLOR.RED,
  },
  {
    mal_id: 50,
    name: 'Adult Cast',
    url: 'https://myanimelist.net/anime/genre/50/Adult_Cast',
    count: 702,
    ...TAG_COLOR.RED,
  },
  {
    mal_id: 51,
    name: 'Anthropomorphic',
    url: 'https://myanimelist.net/anime/genre/51/Anthropomorphic',
    count: 1200,
    ...TAG_COLOR.TOMATO,
  },
  {
    mal_id: 52,
    name: 'CGDCT',
    url: 'https://myanimelist.net/anime/genre/52/CGDCT',
    count: 259,
    ...TAG_COLOR.TOMATO,
  },
  {
    mal_id: 53,
    name: 'Childcare',
    url: 'https://myanimelist.net/anime/genre/53/Childcare',
    count: 76,
    ...TAG_COLOR.BLUE_LIGHT,
  },
  {
    mal_id: 54,
    name: 'Combat Sports',
    url: 'https://myanimelist.net/anime/genre/54/Combat_Sports',
    count: 95,
    ...TAG_COLOR.ORANGE,
  },
  {
    mal_id: 81,
    name: 'Crossdressing',
    url: 'https://myanimelist.net/anime/genre/81/Crossdressing',
    count: 61,
    ...TAG_COLOR.LEMON,
  },
  {
    mal_id: 55,
    name: 'Delinquents',
    url: 'https://myanimelist.net/anime/genre/55/Delinquents',
    count: 76,
    ...TAG_COLOR.BLUE,
  },
  {
    mal_id: 39,
    name: 'Detective',
    url: 'https://myanimelist.net/anime/genre/39/Detective',
    count: 312,
    ...TAG_COLOR.BROWN,
  },
  {
    mal_id: 56,
    name: 'Educational',
    url: 'https://myanimelist.net/anime/genre/56/Educational',
    count: 322,
    ...TAG_COLOR.BLUE,
  },
  {
    mal_id: 57,
    name: 'Gag Humor',
    url: 'https://myanimelist.net/anime/genre/57/Gag_Humor',
    count: 276,
    ...TAG_COLOR.LEMON,
  },
  {
    mal_id: 58,
    name: 'Gore',
    url: 'https://myanimelist.net/anime/genre/58/Gore',
    count: 268,
    ...TAG_COLOR.EMERALD,
  },
  {
    mal_id: 35,
    name: 'Harem',
    url: 'https://myanimelist.net/anime/genre/35/Harem',
    count: 481,
    ...TAG_COLOR.RED,
  },
  {
    mal_id: 59,
    name: 'High Stakes Game',
    url: 'https://myanimelist.net/anime/genre/59/High_Stakes_Game',
    count: 55,
    ...TAG_COLOR.EMERALD,
  },
  {
    mal_id: 13,
    name: 'Historical',
    url: 'https://myanimelist.net/anime/genre/13/Historical',
    count: 1704,
    ...TAG_COLOR.BROWN,
  },
  {
    mal_id: 60,
    name: 'Idols (Female)',
    url: 'https://myanimelist.net/anime/genre/60/Idols_Female',
    count: 360,
    ...TAG_COLOR.PINK,
  },
  {
    mal_id: 61,
    name: 'Idols (Male)',
    url: 'https://myanimelist.net/anime/genre/61/Idols_Male',
    count: 182,
    ...TAG_COLOR.BLUE,
  },
  {
    mal_id: 62,
    name: 'Isekai',
    url: 'https://myanimelist.net/anime/genre/62/Isekai',
    count: 442,
    ...TAG_COLOR.CYAN,
  },
  {
    mal_id: 63,
    name: 'Iyashikei',
    url: 'https://myanimelist.net/anime/genre/63/Iyashikei',
    count: 185,
    ...TAG_COLOR.CYAN,
  },
  {
    mal_id: 64,
    name: 'Love Polygon',
    url: 'https://myanimelist.net/anime/genre/64/Love_Polygon',
    count: 112,
    ...TAG_COLOR.MAGENTA,
  },
  {
    mal_id: 65,
    name: 'Magical Sex Shift',
    url: 'https://myanimelist.net/anime/genre/65/Magical_Sex_Shift',
    count: 32,
    ...TAG_COLOR.MAGENTA,
  },
  {
    mal_id: 66,
    name: 'Mahou Shoujo',
    url: 'https://myanimelist.net/anime/genre/66/Mahou_Shoujo',
    count: 351,
    ...TAG_COLOR.PURPLE,
  },
  {
    mal_id: 17,
    name: 'Martial Arts',
    url: 'https://myanimelist.net/anime/genre/17/Martial_Arts',
    count: 702,
    ...TAG_COLOR.ORANGE,
  },
  {
    mal_id: 18,
    name: 'Mecha',
    url: 'https://myanimelist.net/anime/genre/18/Mecha',
    count: 1309,
    ...TAG_COLOR.DIM,
  },
  {
    mal_id: 67,
    name: 'Medical',
    url: 'https://myanimelist.net/anime/genre/67/Medical',
    count: 56,
    ...TAG_COLOR.BLUE_LIGHT,
  },
  {
    mal_id: 38,
    name: 'Military',
    url: 'https://myanimelist.net/anime/genre/38/Military',
    count: 736,
    ...TAG_COLOR.GREEN,
  },
  {
    mal_id: 19,
    name: 'Music',
    url: 'https://myanimelist.net/anime/genre/19/Music',
    count: 5023,
    ...TAG_COLOR.PURPLE,
  },
  {
    mal_id: 6,
    name: 'Mythology',
    url: 'https://myanimelist.net/anime/genre/6/Mythology',
    count: 646,
    ...TAG_COLOR.BROWN,
  },
  {
    mal_id: 68,
    name: 'Organized Crime',
    url: 'https://myanimelist.net/anime/genre/68/Organized_Crime',
    count: 107,
    ...TAG_COLOR.RED,
  },
  {
    mal_id: 69,
    name: 'Otaku Culture',
    url: 'https://myanimelist.net/anime/genre/69/Otaku_Culture',
    count: 108,
    ...TAG_COLOR.MAGENTA,
  },
  {
    mal_id: 20,
    name: 'Parody',
    url: 'https://myanimelist.net/anime/genre/20/Parody',
    count: 800,
    ...TAG_COLOR.LEMON,
  },
  {
    mal_id: 70,
    name: 'Performing Arts',
    url: 'https://myanimelist.net/anime/genre/70/Performing_Arts',
    count: 123,
    ...TAG_COLOR.BLUE_LIGHT,
  },
  {
    mal_id: 71,
    name: 'Pets',
    url: 'https://myanimelist.net/anime/genre/71/Pets',
    count: 134,
    ...TAG_COLOR.PURPLE,
  },
  {
    mal_id: 40,
    name: 'Psychological',
    url: 'https://myanimelist.net/anime/genre/40/Psychological',
    count: 449,
    ...TAG_COLOR.DIM,
  },
  {
    mal_id: 3,
    name: 'Racing',
    url: 'https://myanimelist.net/anime/genre/3/Racing',
    count: 267,
    ...TAG_COLOR.ORANGE,
  },
  {
    mal_id: 72,
    name: 'Reincarnation',
    url: 'https://myanimelist.net/anime/genre/72/Reincarnation',
    count: 154,
    ...TAG_COLOR.GREY,
  },
  {
    mal_id: 73,
    name: 'Reverse Harem',
    url: 'https://myanimelist.net/anime/genre/73/Reverse_Harem',
    count: 78,
    ...TAG_COLOR.RED,
  },
  {
    mal_id: 74,
    name: 'Love Status Quo',
    url: 'https://myanimelist.net/anime/genre/74/Love_Status_Quo',
    count: 45,
    ...TAG_COLOR.RED,
  },
  {
    mal_id: 21,
    name: 'Samurai',
    url: 'https://myanimelist.net/anime/genre/21/Samurai',
    count: 249,
    ...TAG_COLOR.LIME,
  },
  {
    mal_id: 23,
    name: 'School',
    url: 'https://myanimelist.net/anime/genre/23/School',
    count: 2215,
    ...TAG_COLOR.LIME,
  },
  {
    mal_id: 75,
    name: 'Showbiz',
    url: 'https://myanimelist.net/anime/genre/75/Showbiz',
    count: 50,
    ...TAG_COLOR.LIME,
  },
  {
    mal_id: 29,
    name: 'Space',
    url: 'https://myanimelist.net/anime/genre/29/Space',
    count: 667,
    ...TAG_COLOR.GREY,
  },
  {
    mal_id: 11,
    name: 'Strategy Game',
    url: 'https://myanimelist.net/anime/genre/11/Strategy_Game',
    count: 336,
    ...TAG_COLOR.BLUE,
  },
  {
    mal_id: 31,
    name: 'Super Power',
    url: 'https://myanimelist.net/anime/genre/31/Super_Power',
    count: 717,
    ...TAG_COLOR.MAGENTA,
  },
  {
    mal_id: 76,
    name: 'Survival',
    url: 'https://myanimelist.net/anime/genre/76/Survival',
    count: 75,
    ...TAG_COLOR.BROWN,
  },
  {
    mal_id: 77,
    name: 'Team Sports',
    url: 'https://myanimelist.net/anime/genre/77/Team_Sports',
    count: 323,
    ...TAG_COLOR.LEMON,
  },
  {
    mal_id: 78,
    name: 'Time Travel',
    url: 'https://myanimelist.net/anime/genre/78/Time_Travel',
    count: 154,
    ...TAG_COLOR.LIME,
  },
  {
    mal_id: 32,
    name: 'Vampire',
    url: 'https://myanimelist.net/anime/genre/32/Vampire',
    count: 177,
    ...TAG_COLOR.GREY,
  },
  {
    mal_id: 79,
    name: 'Video Game',
    url: 'https://myanimelist.net/anime/genre/79/Video_Game',
    count: 168,
    ...TAG_COLOR.EMERALD,
  },
  {
    mal_id: 80,
    name: 'Visual Arts',
    url: 'https://myanimelist.net/anime/genre/80/Visual_Arts',
    count: 93,
    ...TAG_COLOR.CYAN,
  },
  {
    mal_id: 48,
    name: 'Workplace',
    url: 'https://myanimelist.net/anime/genre/48/Workplace',
    count: 227,
    ...TAG_COLOR.DIM,
  },
  {
    mal_id: 82,
    name: 'Urban Fantasy',
    url: 'https://myanimelist.net/anime/genre/82/Urban_Fantasy',
    count: 206,
    ...TAG_COLOR.MAGENTA,
  },
  {
    mal_id: 83,
    name: 'Villainess',
    url: 'https://myanimelist.net/anime/genre/83/Villainess',
    count: 26,
    ...TAG_COLOR.RED,
  },
  {
    mal_id: 43,
    name: 'Josei',
    url: 'https://myanimelist.net/anime/genre/43/Josei',
    count: 159,
    ...TAG_COLOR.LEMON,
  },
  {
    mal_id: 15,
    name: 'Kids',
    url: 'https://myanimelist.net/anime/genre/15/Kids',
    count: 6878,
    ...TAG_COLOR.BLUE_LIGHT,
  },
  {
    mal_id: 42,
    name: 'Seinen',
    url: 'https://myanimelist.net/anime/genre/42/Seinen',
    count: 1087,
    ...TAG_COLOR.LIME,
  },
  {
    mal_id: 25,
    name: 'Shoujo',
    url: 'https://myanimelist.net/anime/genre/25/Shoujo',
    count: 516,
    ...TAG_COLOR.RED,
  },
  {
    mal_id: 27,
    name: 'Shounen',
    url: 'https://myanimelist.net/anime/genre/27/Shounen',
    count: 2116,
    ...TAG_COLOR.PURPLE,
  },
];

export default tags;
